// This file was auto-generated by codegen/actionTest.ts. Do not edit.

import { expect, describe, test } from "vitest";

import { findActionFor } from "@/src/lib/trello/action/parse";
import AddMemberToCard from "@/src/lib/trello/action/types/AddMemberToCard";

import payload from "./_payloads/AddMemberToCard.json";
import { getPayloadsExceptFor } from "./common";

describe("AddMemberToCard", () => {
  test("parse empty payload", () => {
    const res = AddMemberToCard.from({});
    expect(res.success, "Parsing empty payload should fail").toBeFalsy();
  });

  test("parse", () => {
    const res = AddMemberToCard.from(payload);
    expect(res.success, "Pre-made JSON payload should parse").toBeTruthy();
  });

  test("find and parse", () => {
    const res = findActionFor(payload);
    expect(
      res,
      "Pre-made JSON payload should resolve to a correct action type"
    ).toBeInstanceOf(AddMemberToCard);
  });

  test("parse wrong payloads", () => {
    const payloads = getPayloadsExceptFor("AddMemberToCard");

    if (payloads.length === 0) {
      console.warn(`AddMemberToCard.test.ts: no wrong payloads to test against`);
      return;
    }

    payloads.forEach(([, payload]) => {
      const res = AddMemberToCard.from(payload);
      expect(res.success, "Parsing wrong payload should fail").toBeFalsy();
    });
  });
});
