// This file was auto-generated by codegen/actionTest.ts. Do not edit.

import { expect, describe, test } from "vitest";

import AddMemberToCard from "@/src/lib/trello/action/types/AddMemberToCard";
import { findActionFor } from "@/src/lib/trello/action/parse";
import { areJSONObjectsEqual, getPayloadsExceptFor } from "./common";

import payload from "./_payloads/AddMemberToCard.json";
import message from "./_messages/AddMemberToCard.json";
        const messageJSONExists = true;

describe("AddMemberToCard", () => {
  test("parse empty payload", () => {
    const res = AddMemberToCard.from({});
    expect(res.success, "Parsing empty payload should fail").toBeFalsy();
  });

  test("parse", () => {
    const res = AddMemberToCard.from(payload);
    expect(res.success, "Pre-made JSON payload should parse").toBeTruthy();
  });

  test.skipIf(!messageJSONExists)("build message", () => {
    const res = AddMemberToCard.from(payload);
    const builtMessage = res.action!.buildMessage({});

    expect(
      builtMessage?.embeds?.length,
      "Messsage should be an embed"
    ).toBeTruthy();

    const embed = builtMessage!.embeds![0];
    embed.setTimestamp(null); /* Ensure no timestamp value present. */

    const cleanEmbed = JSON.parse(JSON.stringify(embed.toJSON()));

    expect(
      areJSONObjectsEqual(cleanEmbed, message),
      "Built message content does not match the expected one"
    ).toBeTruthy();
  });

  test("find and parse", () => {
    const res = findActionFor(payload);
    expect(
      res,
      "Pre-made JSON payload should resolve to a correct action type"
    ).toBeInstanceOf(AddMemberToCard);
  });

  test("parse wrong payloads", () => {
    for (const payload of getPayloadsExceptFor("AddMemberToCard")) {
      const res = AddMemberToCard.from(payload);
      expect(res.success, "Parsing wrong payload should fail").toBeFalsy();
    }
  });
});
