// This file was auto-generated by codegen/actionTest.ts. Do not edit.

import { expect, describe, test } from "vitest";

import MovedCardLower from "@/src/lib/trello/action/types/MovedCardLower";

import { findActionFor } from "@/src/lib/trello/action/parse";
import { areJSONObjectsEqual, getPayloadsExceptFor } from "./common";

import payload from "./_payloads/MovedCardLower.json";
import message from "./_messages/MovedCardLower.json";

const messageJSONExists = true;

describe("MovedCardLower", () => {
  describe("Parsing", () => {
    test("Empty payload", () => {
      const res = MovedCardLower.from({});
      expect(res.success, "Parsing empty payload should fail").toBeFalsy();
    });

    test("Direct", () => {
      const res = MovedCardLower.from(payload);
      expect(res.success, "Pre-made JSON payload should parse").toBeTruthy();
    });

    test("Find type", () => {
      const res = findActionFor(payload);
      expect(
        res,
        "Pre-made JSON payload should resolve to a correct action type"
      ).toBeInstanceOf(MovedCardLower);
    });

    test("Wrong payloads", () => {
      for (const payload of getPayloadsExceptFor("MovedCardLower")) {
        const res = MovedCardLower.from(payload);
        expect(res.success, "Parsing wrong payload should fail").toBeFalsy();
      }
    });
  });

  test.runIf(messageJSONExists)("Build message", async () => {
    const res = MovedCardLower.from(payload);
    const action = res.action!;

    const builtMessage = action.buildMessage({});

    expect(
      builtMessage?.embeds?.length,
      "Messsage should be an embed"
    ).toBeTruthy();

    const embed = builtMessage!.embeds![0];
    embed.setTimestamp(null); /* Ensure no timestamp value present. */

    const cleanEmbed = JSON.parse(JSON.stringify(embed.toJSON()));

    expect(
      areJSONObjectsEqual(cleanEmbed, message),
      "Built message content does not match the expected one"
    ).toBeTruthy();
  });
});
