// This file was auto-generated by codegen/actionTest.ts. Do not edit.

import { expect, describe, test } from "vitest";

import { findActionFor } from "@/src/lib/trello/action/parse";
import RemoveCheckListFromCard from "@/src/lib/trello/action/types/RemoveCheckListFromCard";

import payload from "./_payloads/RemoveCheckListFromCard.json";
import { getPayloadsExceptFor } from "./common";

describe("RemoveCheckListFromCard", () => {
  test("parse empty payload", () => {
    const res = RemoveCheckListFromCard.from({});
    expect(res.success, "Parsing empty payload should fail").toBeFalsy();
  });

  test("parse", () => {
    const res = RemoveCheckListFromCard.from(payload);
    expect(res.success, "Pre-made JSON payload should parse").toBeTruthy();

    const message = res.action?.buildMessage({});
    expect(message, "Built message should be truthy").toBeTruthy();
  });

  test("find and parse", () => {
    const res = findActionFor(payload);
    expect(
      res,
      "Pre-made JSON payload should resolve to a correct action type"
    ).toBeInstanceOf(RemoveCheckListFromCard);
  });

  test("parse wrong payloads", () => {
    for (const payload of getPayloadsExceptFor("RemoveCheckListFromCard")) {
      const res = RemoveCheckListFromCard.from(payload);
      expect(res.success, "Parsing wrong payload should fail").toBeFalsy();
    }
  });
});
