// This file was auto-generated by codegen/actionTest.ts. Do not edit.

import { expect, describe, test } from "vitest";

import { findActionFor } from "@/src/lib/trello/action/parse";
import RenamedCheckItem from "@/src/lib/trello/action/types/RenamedCheckItem";

import payload from "./_payloads/RenamedCheckItem.json";
import { getPayloadsExceptFor } from "./common";

describe("RenamedCheckItem", () => {
  test("parse empty payload", () => {
    const res = RenamedCheckItem.from({});
    expect(res.success, "Parsing empty payload should fail").toBeFalsy();
  });

  test("parse", () => {
    const res = RenamedCheckItem.from(payload);
    expect(res.success, "Pre-made JSON payload should parse").toBeTruthy();

    const message = res.action?.buildMessage({});
    expect(message, "Built message should be truthy").toBeTruthy();
  });

  test("find and parse", () => {
    const res = findActionFor(payload);
    expect(
      res,
      "Pre-made JSON payload should resolve to a correct action type"
    ).toBeInstanceOf(RenamedCheckItem);
  });

  test("parse wrong payloads", () => {
    const payloads = getPayloadsExceptFor("RenamedCheckItem");

    if (payloads.length === 0) {
      console.warn(`RenamedCheckItem.test.ts: no wrong payloads to test against`);
      return;
    }

    payloads.forEach(([, payload]) => {
      const res = RenamedCheckItem.from(payload);
      expect(res.success, "Parsing wrong payload should fail").toBeFalsy();
    });
  });
});
