/**
 * Copyright (c) 2025 Kiril Strezikozin
 *
 * SPDX-License-Identifier: MIT
 *
 * You may not use this file except in compliance with the MIT license terms.
 */

/** Generates a list of all Trello action types described in this project. */

import * as fs from "fs";
import * as path from "path";

const actionTypesDirectory = "./src/lib/trello/action/types/";
const actionLibDirectory = "./src/lib/trello/action/";
const filePath = actionLibDirectory + "types.ts";

/* Collect filenames that start with a capital letter. */
const actionTypeNames = fs.readdirSync(actionTypesDirectory).map((value) => {
  return path.parse(value).name;
}).filter((value) => (/^[A-Z]$/.test(value[0])));

const fileData = `
// This file was auto-generated by codegen/actionList.ts. Do not edit.

import { Action } from "./types/base";

`.trimStart()
  + actionTypeNames.map((name) => `import ${name} from "./types/${name}";`).join("\n")
  + `

/**
 * List of all Action types in the library.
 */
export const ActionTypes: (typeof Action)[] = [
`
  + actionTypeNames.map((name) => `  ${name},`).join("\n")
  + `\n];`;

fs.writeFileSync(filePath, fileData, "utf-8");

console.log(`codegen/actionList.ts wrote to ${filePath}`);
console.log("The following Trelo action types were collected:");
console.log(actionTypeNames);