/**
 * Copyright (c) 2025 Kiril Strezikozin
 *
 * SPDX-License-Identifier: MIT
 *
 * You may not use this file except in compliance with the MIT license terms.
 */

/** Generates a list of all Trello action types described in this project. */

import * as fs from "fs";
import * as path from "path";

import { green, bold } from "console-log-colors";
import { typesDirectory } from "@/test/lib/trello/action/types/common";

const actionLibDirectory = "./src/lib/trello/action/";
const filePath = actionLibDirectory + "types.ts";

/* Collect all activity type names. */
const typeNames = fs.readdirSync(typesDirectory)
  .map(filePath => path.parse(filePath).name)
  .filter(filePath => /^[A-Z]$/.test(filePath[0]));

const fileData = `
// This file was auto-generated by codegen/actionList.ts. Do not edit.

import { Action } from "./types/base";

`.trimStart()
  + typeNames.map((name) => `import ${name} from "./types/${name}";`).join("\n")
  + `

/**
 * List of all Action types in the library.
 */
export const ActionTypes: (typeof Action)[] = [
`
  + typeNames.map((name) => `  ${name},`).join("\n")
  + `\n];`;

fs.writeFileSync(filePath, fileData, "utf-8");

console.log(bold(green(`actionList.ts: ${filePath} was written`)));
console.log(`actionList.ts: The following ${typeNames.length} Trelo action types were collected:`);
console.log(typeNames);