// This file was auto-generated by codegen/actionList.ts. Do not edit.

import { Action } from "./types/base";

import AddAttachmentToCard from "./types/AddAttachmentToCard";
import AddCheckListToCard from "./types/AddCheckListToCard";
import AddMemberToCard from "./types/AddMemberToCard";
import AddedCardCover from "./types/AddedCardCover";
import AddedCardDueDate from "./types/AddedCardDueDate";
import AddedCardStartDate from "./types/AddedCardStartDate";
import ArchivedCard from "./types/ArchivedCard";
import ChangedCardDueDate from "./types/ChangedCardDueDate";
import ChangedCardDueDateReminder from "./types/ChangedCardDueDateReminder";
import ChangedCardStartDate from "./types/ChangedCardStartDate";
import ChangedDescriptionOfCard from "./types/ChangedDescriptionOfCard";
import CompletedCheckItem from "./types/CompletedCheckItem";
import CreateCard from "./types/CreateCard";
import CreateCheckItem from "./types/CreateCheckItem";
import DeletedCheckItem from "./types/DeletedCheckItem";
import MarkedCheckItemIncomplete from "./types/MarkedCheckItemIncomplete";
import MoveCardFromListToList from "./types/MoveCardFromListToList";
import MovedCardHigher from "./types/MovedCardHigher";
import MovedCardLower from "./types/MovedCardLower";
import MovedCheckItemHigher from "./types/MovedCheckItemHigher";
import MovedCheckItemLower from "./types/MovedCheckItemLower";
import RemoveCheckListFromCard from "./types/RemoveCheckListFromCard";
import RemoveMemberFromCard from "./types/RemoveMemberFromCard";
import RemovedCardDueDate from "./types/RemovedCardDueDate";
import RemovedCardStartDate from "./types/RemovedCardStartDate";
import RenamedCard from "./types/RenamedCard";
import RenamedCheckItem from "./types/RenamedCheckItem";
import VoteOnCard from "./types/VoteOnCard";

/**
 * List of all Action types in the library.
 */
export const ActionTypes: (typeof Action)[] = [
  AddAttachmentToCard,
  AddCheckListToCard,
  AddMemberToCard,
  AddedCardCover,
  AddedCardDueDate,
  AddedCardStartDate,
  ArchivedCard,
  ChangedCardDueDate,
  ChangedCardDueDateReminder,
  ChangedCardStartDate,
  ChangedDescriptionOfCard,
  CompletedCheckItem,
  CreateCard,
  CreateCheckItem,
  DeletedCheckItem,
  MarkedCheckItemIncomplete,
  MoveCardFromListToList,
  MovedCardHigher,
  MovedCardLower,
  MovedCheckItemHigher,
  MovedCheckItemLower,
  RemoveCheckListFromCard,
  RemoveMemberFromCard,
  RemovedCardDueDate,
  RemovedCardStartDate,
  RenamedCard,
  RenamedCheckItem,
  VoteOnCard,
];