// This file was auto-generated by codegen/actionList.ts. Do not edit.

import { Action } from "./types/base";

import AddAttachmentToCard from "./types/AddAttachmentToCard";
import AddCheckListToCard from "./types/AddCheckListToCard";
import AddLabelToCard from "./types/AddLabelToCard";
import AddMemberToBoard from "./types/AddMemberToBoard";
import AddMemberToCard from "./types/AddMemberToCard";
import AddedCardCover from "./types/AddedCardCover";
import AddedCardDueDate from "./types/AddedCardDueDate";
import AddedCardStartDate from "./types/AddedCardStartDate";
import ArchivedCard from "./types/ArchivedCard";
import ArchivedList from "./types/ArchivedList";
import ChangedCardCover from "./types/ChangedCardCover";
import ChangedCardCoverProperties from "./types/ChangedCardCoverProperties";
import ChangedCardDueDate from "./types/ChangedCardDueDate";
import ChangedCardDueDateReminder from "./types/ChangedCardDueDateReminder";
import ChangedCardStartDate from "./types/ChangedCardStartDate";
import ChangedDescriptionOfBoard from "./types/ChangedDescriptionOfBoard";
import ChangedDescriptionOfCard from "./types/ChangedDescriptionOfCard";
import ClosedBoard from "./types/ClosedBoard";
import CommentOnCard from "./types/CommentOnCard";
import CompletedCheckItem from "./types/CompletedCheckItem";
import ConvertToCardFromCheckItem from "./types/ConvertToCardFromCheckItem";
import CopyCard from "./types/CopyCard";
import CopyCheckList from "./types/CopyCheckList";
import CopyCommentFromCard from "./types/CopyCommentFromCard";
import CreateCard from "./types/CreateCard";
import CreateCheckItem from "./types/CreateCheckItem";
import CreateLabel from "./types/CreateLabel";
import CreateList from "./types/CreateList";
import DeleteAttachmentFromCard from "./types/DeleteAttachmentFromCard";
import DeleteCard from "./types/DeleteCard";
import DeleteComment from "./types/DeleteComment";
import DeleteLabel from "./types/DeleteLabel";
import DeleteList from "./types/DeleteList";
import DeletedCheckItem from "./types/DeletedCheckItem";
import EmailCard from "./types/EmailCard";
import MakeAdminOfBoard from "./types/MakeAdminOfBoard";
import MakeNormalMemberOfBoard from "./types/MakeNormalMemberOfBoard";
import MarkedCardComplete from "./types/MarkedCardComplete";
import MarkedCardIncomplete from "./types/MarkedCardIncomplete";
import MarkedCheckItemIncomplete from "./types/MarkedCheckItemIncomplete";
import MoveCardFromBoard from "./types/MoveCardFromBoard";
import MoveCardFromListToList from "./types/MoveCardFromListToList";
import MoveCardToBoard from "./types/MoveCardToBoard";
import MoveListToBoard from "./types/MoveListToBoard";
import MovedCardHigher from "./types/MovedCardHigher";
import MovedCardLower from "./types/MovedCardLower";
import MovedCheckItemHigher from "./types/MovedCheckItemHigher";
import MovedCheckItemLower from "./types/MovedCheckItemLower";
import MovedListLeft from "./types/MovedListLeft";
import MovedListRight from "./types/MovedListRight";
import RemoveCheckListFromCard from "./types/RemoveCheckListFromCard";
import RemoveLabelFromCard from "./types/RemoveLabelFromCard";
import RemoveMemberFromBoard from "./types/RemoveMemberFromBoard";
import RemoveMemberFromCard from "./types/RemoveMemberFromCard";
import RemovedCardDueDate from "./types/RemovedCardDueDate";
import RemovedCardStartDate from "./types/RemovedCardStartDate";
import RemovedVoteFromCard from "./types/RemovedVoteFromCard";
import RenamedBoard from "./types/RenamedBoard";
import RenamedCard from "./types/RenamedCard";
import RenamedCheckItem from "./types/RenamedCheckItem";
import RenamedCheckList from "./types/RenamedCheckList";
import RenamedList from "./types/RenamedList";
import ReopenedBoard from "./types/ReopenedBoard";
import RestoredCard from "./types/RestoredCard";
import RestoredList from "./types/RestoredList";
import SetAttachmentAsCardCover from "./types/SetAttachmentAsCardCover";
import UnsetAttachmentAsCardCover from "./types/UnsetAttachmentAsCardCover";
import UpdateCardLabels from "./types/UpdateCardLabels";
import UpdateComment from "./types/UpdateComment";
import UpdateLabelColor from "./types/UpdateLabelColor";
import UpdateLabelName from "./types/UpdateLabelName";
import VoteOnCard from "./types/VoteOnCard";

/**
 * List of all Action types in the library.
 */
export const ActionTypes: (typeof Action)[] = [
  AddAttachmentToCard,
  AddCheckListToCard,
  AddLabelToCard,
  AddMemberToBoard,
  AddMemberToCard,
  AddedCardCover,
  AddedCardDueDate,
  AddedCardStartDate,
  ArchivedCard,
  ArchivedList,
  ChangedCardCover,
  ChangedCardCoverProperties,
  ChangedCardDueDate,
  ChangedCardDueDateReminder,
  ChangedCardStartDate,
  ChangedDescriptionOfBoard,
  ChangedDescriptionOfCard,
  ClosedBoard,
  CommentOnCard,
  CompletedCheckItem,
  ConvertToCardFromCheckItem,
  CopyCard,
  CopyCheckList,
  CopyCommentFromCard,
  CreateCard,
  CreateCheckItem,
  CreateLabel,
  CreateList,
  DeleteAttachmentFromCard,
  DeleteCard,
  DeleteComment,
  DeleteLabel,
  DeleteList,
  DeletedCheckItem,
  EmailCard,
  MakeAdminOfBoard,
  MakeNormalMemberOfBoard,
  MarkedCardComplete,
  MarkedCardIncomplete,
  MarkedCheckItemIncomplete,
  MoveCardFromBoard,
  MoveCardFromListToList,
  MoveCardToBoard,
  MoveListToBoard,
  MovedCardHigher,
  MovedCardLower,
  MovedCheckItemHigher,
  MovedCheckItemLower,
  MovedListLeft,
  MovedListRight,
  RemoveCheckListFromCard,
  RemoveLabelFromCard,
  RemoveMemberFromBoard,
  RemoveMemberFromCard,
  RemovedCardDueDate,
  RemovedCardStartDate,
  RemovedVoteFromCard,
  RenamedBoard,
  RenamedCard,
  RenamedCheckItem,
  RenamedCheckList,
  RenamedList,
  ReopenedBoard,
  RestoredCard,
  RestoredList,
  SetAttachmentAsCardCover,
  UnsetAttachmentAsCardCover,
  UpdateCardLabels,
  UpdateComment,
  UpdateLabelColor,
  UpdateLabelName,
  VoteOnCard,
];